# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "gapi"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Bovensiepen", "Dingding Ye"]
  s.date = "2012-11-16"
  s.email = "daniel@bovensiepen.net"
  s.extra_rdoc_files = [
    "ChangeLog",
    "README"
  ]
  s.files = [
    "ChangeLog",
    "Gemfile",
    "MIT-LICENSE",
    "README",
    "Rakefile",
    "VERSION",
    "lib/gapi.rb",
    "lib/gapi/language.rb",
    "lib/gapi/web.rb",
    "tests/detect_test.rb",
    "tests/search_test.rb",
    "tests/test_helper.rb",
    "tests/translate_test.rb"
  ]
  s.homepage = "https://github.com/bovi/gapi"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Google API wrapper for Search and Translate"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<json_pure>, [">= 0"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<json_pure>, [">= 0"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<json_pure>, [">= 0"])
  end
end

